### PR TITLE
Added linaria example

### PR DESCRIPTION
**Pull request by danpetrv**
Hi, thanks for interesting overview! Decided to add linaria example.

### CODE REVIEW

**Comment by andreipfeiffer** [comment]
Hey Daniil,
Thank you for the PR.

I will look over it and merge it into a separate branch, like the other examples and then provide a review of the lib.

However, I'm pretty busy this week, so I'll have to delay it until next week.
I'll port the update here.

Thank you once again,
Andrei

**Comment by danpetrv** [comment]
Thanks! The current linaria example inside nextjs repo is not working correctly during the build step, so I added separate next-linaria.js, that supports linaria version 3

**Comment by andreipfeiffer** [comment]
Yes, that's exactly why I haven't included Linaria in my initial analysis.
So, thank you for that.

**Comment by andreipfeiffer** [comment]
Hey @daniepetrov I've managed to implement a fully working example here:
https://github.com/andreipfeiffer/css-in-js/tree/linaria

Review coming later today

NOTE: do you know how to make global styles work with Next.js? This doesn't work for me: https://github.com/callstack/linaria/blob/master/docs/BASICS.md#adding-global-styles

**Comment by andreipfeiffer** [comment]
Linaria review added as well: https://github.com/andreipfeiffer/css-in-js/blob/main/README.md#linaria

**Comment by andreipfeiffer** [comment]
I'll close this PR, thank you again @daniepetrov

**Comment by danpetrv** [comment]
@andreipfeiffer, unfortunately, don't know how to make them work. There is the [issue about the bug](https://github.com/callstack/linaria/issues/724). Thanks! 😀

**Comment by andreipfeiffer** [comment]
Hmmm, just curious: have you tried https://github.com/Mistereo/next-linaria?
It is linked in the issue that you mentioned

**Pull request closed without merging**
